
try:
    something()
except:
    pass

try:
    something()
except Exception as e:
    pass
    # test
    pass